[env]
TERM = "xterm-256color"

[font]
size = 12

[font.normal]
# family = "BlexMono Nerd Font Mono"
# family = "JetBrains Mono Nerd Font"
# family = "MesloLGS NF"
# family = "MonaspiceAr Nerd Font Mono"
family = "CaskaydiaCove Nerd Font Mono"

[terminal.shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/usr/bin/zsh"

[window]
dynamic_padding = true
decorations = "none"
startup_mode = "Maximized"
opacity = 0.8
padding = { x=8, y=8 }

[general]
import = ["~/.config/alacritty/themes/rose-pine.toml"]
